### ISSUE TITLE
Please start navigation menu

### ISSUE THREAD

**Issue by edoves** [edoves/team_cocktail_proj#11]
@dextersigue ang galing mo sa header! ngayon naman paki simulan na ang navigation menu
![menu](https://user-images.githubusercontent.com/14107715/189595120-5bba95d8-f000-46fa-99b2-bafd54d20d46.JPG)

**Comment by dextersigue** [comment]
Thanks @edoves gawin ko na ngayon im so excited.

**Comment by dextersigue** [comment]
@edoves na push ko na ang navigation menu please check it thanks.

**Comment by edoves** [comment]
@dextersigue salamat merged na napaka husay mo isa kang alamat
