### ISSUE TITLE
Please start creating the footer

### ISSUE THREAD

**Issue by edoves** [edoves/team_cocktail_proj#12]
@dextersigue paki code na din ang footer at gawin mong dynamic yung year salamat
![footer](https://user-images.githubusercontent.com/14107715/189800217-bae103da-6521-4873-90ed-aabd520287b7.JPG)

**Comment by dextersigue** [comment]
@edoves Gagawin ko na yong Footer

**Comment by dextersigue** [comment]
@edoves Nagawa ko na ang Footer Please check Thanks.

**Comment by edoves** [comment]
amazing magnificent so smart
