### ISSUE TITLE
please start creating the hero area

### ISSUE THREAD

**Issue by edoves** [edoves/team_cocktail_proj#19]
@dextersigue eto na ang hero area pwede mo ng simulan
![heroarea](https://user-images.githubusercontent.com/14107715/189887697-759e6cb0-51f8-4de9-af99-190feb5b32ed.JPG)

**Comment by dextersigue** [comment]
sige @edoves  salamat sisimulan ko na

**Comment by dextersigue** [comment]
@edoves na push ko na ang hero Please Check Thanks.

**Comment by edoves** [comment]
salamat galing mo
