### ISSUE TITLE
start coding the category menu

### ISSUE THREAD

**Issue by edoves** [edoves/team_cocktail_proj#20]
@emman355 355 this is bro tapos na si dexter hero area na lang natira para sa pwede na tayo mag code pwede mo ng simulan yun category menu. please confirm by simply commenting
![category menu](https://user-images.githubusercontent.com/14107715/189891651-1000733c-18f6-4ee3-8b57-79f714e3f1fb.JPG)

**Comment by emman355** [comment]
simulan kona

**Comment by edoves** [comment]
wonderful

**Comment by emman355** [comment]
category-menu feature done!

**Comment by edoves** [comment]
@emman355 thanks man
