### ISSUE TITLE
start coding the category cards

### ISSUE THREAD

**Issue by edoves** [edoves/team_cocktail_proj#25]
@emman355 next mo na to man
![category card](https://user-images.githubusercontent.com/14107715/190121064-bc75332a-3eb4-491a-ad4c-79c3183b0780.JPG)

**Comment by emman355** [comment]
on progress

**Comment by emman355** [comment]
category cards #25 done!

**Comment by edoves** [comment]
already merged pero may error sa pag call ng api hahahaha naka localhost ka pala hindi pala yan gagana pag nasa staging na
![306603424_1508558936249731_5176050300235169270_n](https://user-images.githubusercontent.com/14107715/190343255-b85f14fa-0734-4ac0-bbbb-4726a436b7fd.png)
