### ISSUE TITLE
please start working with category thumbnail

### ISSUE THREAD

**Issue by edoves** [edoves/team_cocktail_proj#40]
@dextersigue dext simulan mo gawin yung categoty thumbnail sa may singlepage.html gawin mo lang muna yung UI
![category thumbnail](https://user-images.githubusercontent.com/14107715/190936894-ee5c7ca4-dc0d-4bb2-a993-d5d54c6dd259.JPG)

**Comment by dextersigue** [comment]
@edoves sige simulan ko na category thumbnail

**Comment by dextersigue** [comment]
@edoves na push ko na category thumbnail Please check Thanks.

**Comment by edoves** [comment]
wonderful! already merged
