### ISSUE TITLE
start creating the cocktail name page and create the search box inside it

### ISSUE THREAD

**Issue by edoves** [edoves/team_cocktail_proj#44]
@dextersigue simulan mo na to dext please
![search box](https://user-images.githubusercontent.com/14107715/191141659-3118b9c1-3c28-4dff-a382-32f78c5584ce.JPG)

**Comment by dextersigue** [comment]
@edoves sige simulan ko na ngayon.

**Comment by edoves** [comment]
sipag ah

**Comment by dextersigue** [comment]
@edoves na push ko na ang Search box

**Comment by edoves** [comment]
checking

**Comment by edoves** [comment]
merged
