### ISSUE TITLE
fixed home page unusual layout

### ISSUE THREAD

**Issue by edoves** [edoves/team_cocktail_proj#49]
@dextersigue eto dext paki fix
![home page](https://user-images.githubusercontent.com/14107715/191415915-1d929bcf-c164-43b0-b626-9501704ec843.JPG)

**Comment by dextersigue** [comment]
@edoves sige simulan ko na i fix. thanks

**Comment by edoves** [comment]
salamat sa pag accept ng napaka hirap na task na ito sir @dextersigue na appreciate ko lahat ng mga ginagawa mo

**Comment by dextersigue** [comment]
@edoves na push ko na please check thanks.

**Comment by edoves** [comment]
magaling mahusay
