### ISSUE TITLE
fix navigation menu both mobile and desktop view

### ISSUE THREAD

**Issue by edoves** [edoves/team_cocktail_proj#50]
@dextersigue paki ayos naman yung desktop view ng menu natin saka mobile view, yung hamburger menu looks odd and it has an unexpected behavior na cclick lang sa may line hindi mismo doon sa div 

![desktop view menu](https://user-images.githubusercontent.com/14107715/191416624-f0f0432a-fcba-4e67-8b10-31aafe81ddd1.JPG)
![mobile view menu](https://user-images.githubusercontent.com/14107715/191416638-8e09b20a-0886-41c9-a36d-a3ebb8288d9d.JPG)

**Comment by dextersigue** [comment]
@edoves sige simulan ko na i fix. thanks

**Comment by edoves** [comment]
salamat ng marami sa ginagawa mong effort ng pag cocode

**Comment by dextersigue** [comment]
@edoves na push ko na Please Check. Thanks

**Comment by edoves** [comment]
checking
