### ISSUE TITLE
start developing the cards ui in cocktail page

### ISSUE THREAD

**Issue by edoves** [edoves/team_cocktail_proj#59]
@dextersigue tirahin mo to ngayon
![cocktail](https://user-images.githubusercontent.com/14107715/191624737-d31af62f-3794-48a3-9f7d-147a6461a021.JPG)

**Comment by dextersigue** [comment]
@edoves umpisahan ko na to ngayon

**Comment by dextersigue** [comment]
@edoves na push ko please check. thanks

**Comment by edoves** [comment]
@dextersigue paki fix naman gawa mo please tignan mo mabuti ang design bago ka mag push tignan mo kung parehas sa dinidevelop mo

**Comment by edoves** [comment]
salamat  @dextersigue  ang galing mo
