### ISSUE TITLE
Start creating header

### ISSUE THREAD

**Issue by edoves** [edoves/team_cocktail_proj#7]
@dextersigue dext simulan mo na ang header
![header](https://user-images.githubusercontent.com/14107715/189511384-4c1616d2-34a3-4768-9477-beb38570e04e.JPG)

**Comment by dextersigue** [comment]
@edoves sisimulan ko yong header

**Comment by edoves** [comment]
@dextersigue eto yung mga social media icons para hindi ka na mahirapan pa sa pag hahanap ng svg icon ako na nag hanap. aralin mo kung paano nilalagay ang svg icon or image sa website madaming youtube tutorial para jan hindi ka mauubusan ng info
![entypo-social_dribbble-with-circle](https://user-images.githubusercontent.com/14107715/189515754-f1ab3be0-9674-4280-aa56-ecfe1bcf5c2c.svg)
![eva_behance-fill](https://user-images.githubusercontent.com/14107715/189515758-4d0d07a9-2163-45d9-8eb8-fe0c6f6beb7a.svg)
![entypo-social_facebook-with-circle](https://user-images.githubusercontent.com/14107715/189515761-02d4488c-96b1-4f47-a6c9-c217d3b42ee2.svg)
![entypo-social_twitter-with-circle](https://user-images.githubusercontent.com/14107715/189515767-a57ab80e-25ab-490c-964a-5b0a14acb00d.svg)
![typcn_social-youtube-circular](https://user-images.githubusercontent.com/14107715/189515769-5f971872-8774-408a-9008-87ca75495ee2.svg)

**Comment by dextersigue** [comment]
yon salamat dove haha

**Comment by dextersigue** [comment]
@edoves  tapos na yong Header.

Please Check

**Comment by edoves** [comment]
@dextersigue magnificent!!! one of a kind.
